// 仅导入项目实际使用的 MDI 图标（SVG 路径），替代全量 @mdi/font 字体加载
// 全量字体约 400KB+，按需 SVG 仅几 KB，大幅提升首屏加载速度
import { h } from 'vue'
import { mdi } from 'vuetify/iconsets/mdi-svg'
import {
  mdiGithub,
  mdiEmail,
  mdiQqchat,
  mdiWechat,
  mdiYoutube,
  mdiFacebook,
  mdiVuejs,
  mdiLanguageJavascript,
  mdiLanguageCss3,
  mdiLanguageHtml5,
  mdiPencilPlus,
  mdiWallpaper,
  mdiMusicCircleOutline,
  mdiSkipPrevious,
  mdiPause,
  mdiPlay,
  mdiSkipNext,
  mdiVolumeOff,
  mdiVolumeLow,
  mdiVolumeHigh,
  mdiCog,
  mdiKeyChain,
  mdiInformation,
  mdiLockReset,
  mdiCertificate,
  mdiMaterialDesign,
  mdiChartLine,
  mdiMusic,
  mdiPalette,
  mdiTagMultiple,
  mdiClose,
  mdiDelete,
  mdiPlus,
  mdiContentSave,
  mdiPencil,
  mdiPlusCircle,
  mdiLock,
  mdiCheckCircle,
  mdiLogin,
  mdiLogout,
  mdiAlertCircle,
  mdiEyeOff,
  mdiEye,
  mdiText,
  mdiImagePlus,
  mdiKeyboard,
  mdiChevronDown,
  mdiEarth,
  mdiMagnify,
  mdiWebhook,
  mdiChevronUp,
  mdiArrowDown,
  mdiPanoramaVariantOutline,
  mdiVideoInputSvideo,
} from '@mdi/js'

// 将 mdi-xxx 名称映射到 SVG 路径
export const iconAliases = {
  'mdi-github': mdiGithub,
  'mdi-email': mdiEmail,
  'mdi-qqchat': mdiQqchat,
  'mdi-wechat': mdiWechat,
  'mdi-youtube': mdiYoutube,
  'mdi-facebook': mdiFacebook,
  'mdi-vuejs': mdiVuejs,
  'mdi-language-javascript': mdiLanguageJavascript,
  'mdi-language-css3': mdiLanguageCss3,
  'mdi-language-html5': mdiLanguageHtml5,
  'mdi-pencil-plus': mdiPencilPlus,
  'mdi-wallpaper': mdiWallpaper,
  'mdi-music-circle-outline': mdiMusicCircleOutline,
  'mdi-skip-previous': mdiSkipPrevious,
  'mdi-pause': mdiPause,
  'mdi-play': mdiPlay,
  'mdi-skip-next': mdiSkipNext,
  'mdi-volume-off': mdiVolumeOff,
  'mdi-volume-low': mdiVolumeLow,
  'mdi-volume-high': mdiVolumeHigh,
  'mdi-cog': mdiCog,
  'mdi-key-chain': mdiKeyChain,
  'mdi-information': mdiInformation,
  'mdi-lock-reset': mdiLockReset,
  'mdi-certificate': mdiCertificate,
  'mdi-material-design': mdiMaterialDesign,
  'mdi-chart-line': mdiChartLine,
  'mdi-music': mdiMusic,
  'mdi-palette': mdiPalette,
  'mdi-tag-multiple': mdiTagMultiple,
  'mdi-close': mdiClose,
  'mdi-delete': mdiDelete,
  'mdi-plus': mdiPlus,
  'mdi-content-save': mdiContentSave,
  'mdi-pencil': mdiPencil,
  'mdi-plus-circle': mdiPlusCircle,
  'mdi-lock': mdiLock,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-login': mdiLogin,
  'mdi-logout': mdiLogout,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-eye-off': mdiEyeOff,
  'mdi-eye': mdiEye,
  'mdi-text': mdiText,
  'mdi-image-plus': mdiImagePlus,
  'mdi-keyboard': mdiKeyboard,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-earth': mdiEarth,
  'mdi-magnify': mdiMagnify,
  'mdi-webhook': mdiWebhook,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-arrow-down': mdiArrowDown,
  'mdi-panorama-variant-outline': mdiPanoramaVariantOutline,
  'mdi-video-input-svideo': mdiVideoInputSvideo,
}

// 自定义 mdi 图标集：自动将 mdi-xxx 名称解析为 SVG 路径
// 这样模板中可继续使用 <v-icon>mdi-close</v-icon> 字符串形式，无需加 $ 前缀
export const mdiIconSet = {
  component: (props) => {
    const iconName = props.icon
    const resolvedIcon =
      typeof iconName === 'string' && iconAliases[iconName]
        ? iconAliases[iconName]
        : iconName
    return h(mdi.component, { ...props, icon: resolvedIcon })
  },
}
